# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 风雪夜归人
email: i@lutaoact.com
description: > # this means to ignore newlines until "baseurl:"
  柴门闻犬吠 风雪夜归人
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.lutaoact.com" # the base hostname & protocol for your site
github_username: lutaoact
timezone: Asia/Shanghai
encoding: UTF-8

# Build settings
markdown: kramdown
